import { Injectable, Inject } from '@angular/core';
import { APP_CONFIG, AppConfig } from './app-config.interface';
//this might not be needed, may be a redundant file generated by ai.

@Injectable({
  providedIn: 'root'
})
export class ConfigService {
  
  constructor(@Inject(APP_CONFIG) private config: AppConfig) {}

  // API Configuration
  get ibApiUrl(): string {
    return this.config.api.ibApiUrl;
  }

  get fastApiUrl(): string {
    return this.config.api.fastApiUrl;
  }

  get apiTimeout(): number {
    return this.config.api.timeout;
  }

  get retryAttempts(): number {
    return this.config.api.retryAttempts;
  }

  // Trading Configuration
  get maxRiskPerTrade(): number {
    return this.config.trading.maxRiskPerTrade;
  }

  get defaultSymbols(): string[] {
    return this.config.trading.defaultSymbols;
  }

  get paperTrading(): boolean {
    return this.config.trading.paperTrading;
  }

  get defaultAccountId(): string {
    return this.config.trading.defaultAccountId;
  }

  // Feature Flags
  get enableMockData(): boolean {
    return this.config.features.enableMockData;
  }

  get enableLogging(): boolean {
    return this.config.features.enableLogging;
  }

  get enableRealTimeData(): boolean {
    return this.config.features.enableRealTimeData;
  }

  // Environment
  get isProduction(): boolean {
    return this.config.production;
  }

  // Utility methods
  getFullConfig(): AppConfig {
    return this.config;
  }

  log(message: string, data?: any): void {
    if (this.enableLogging) {
      console.log(`[ConfigService] ${message}`, data);
    }
  }
}
